# Site settings
title: Fornebu Padel
email: info@fornebupadel.no
description: > # this means to ignore newlines until "baseurl:"
  Fornebu Padel tilbyr tre flotte padelbaner til utleie året rundt. Fornebu Padel deler lokale med Fornebu Indoor Golf Center. Baner kan leies enkelt på web. Utstyr som racketer og baller kan leies eller kjøpes i butikken.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username: fornebu-padel
matchi_fp_url: https://www.matchi.se/facilities/fornebupadel

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

exclude: [node_modules]
